apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wqp0i06-q-go
  janus-idp.io/tekton: wqp0i06-q-go
  backstage.io/kubernetes-id: wqp0i06-q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wqp0i06-q-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
